# Generated by Django 3.1.2 on 2020-10-15 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='hour',
            field=models.TimeField(default=datetime.datetime(2020, 10, 15, 16, 42, 17, 836437)),
        ),
    ]
