# Generated by Django 3.1.2 on 2020-10-15 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20201015_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='day',
            field=models.IntegerField(default='<built-in method time of datetime.datetime object at 0x7f54a123df30>'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hour',
            field=models.TimeField(default=datetime.datetime(2020, 10, 15, 16, 46, 47, 480954)),
        ),
    ]
