# Generated by Django 3.1.2 on 2020-10-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20201015_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hour',
            field=models.TimeField(default='django.utils.timezone.now'),
        ),
    ]
